name: Docker
run-name: 'build(docker): image for `${{ github.ref_name }}`'

on:
  # push:
  #   branches: [starter/*]
  workflow_call:
  # workflow_run:
  #   workflows: [CI]
  #   types: [completed]
  #   branches: [starter/*]

jobs:
  image:
    name: Image
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name != 'pull_request' }}
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_REGISTRY: ghcr.io
      IMAGE_NAME: feryardiant/laravel-12

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        # with:
        #   ref: ${{ github.event.workflow_run.head_branch }}

      - name: Download assets
        uses: actions/download-artifact@v4
        with:
          name: build-testing
          path: public

      - name: Login to ${{ env.IMAGE_REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Generate meta data
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          file: .deploy/production/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
